<a href="https://colab.research.google.com/github/abhinav-bhardwaj-mnit/Abhinav-1st/blob/main/multiple_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import copy,math
import numpy as np
import matplotlib.pyplot as plt
np.set_printoptions(precision=2)  # reduced display precision on numpy arrays

In [21]:
X_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
y_train = np.array([460, 232, 178])
print(X_train)
print(y_train)
b_init = 5
w_init = np.array([.39,.2,1,5.4])
print(f"w_init shape: {w_init.shape}")
np.shape(y_train)

[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
[460 232 178]
w_init shape: (4,)


(3,)

In [34]:
def oneloop(w,x,b):
  (cost) = 0
  for i in range(len(y_train)):
    y_pred = np.dot(w,x[i])+b
    cost = cost + (y_pred-y_train[i])**2
    print(i)
    print(y_pred)
  cost_fn = cost/(2*len(y_train))
  print(f"cost_fn:{cost_fn}")
  return cost_fn
oneloop(w_init,X_train,b_init)

0
1070.5600000000002
1
775.84
2
527.6800000000001
131803.59360000005
cost_fn:131803.59360000005


np.float64(131803.59360000005)

In [62]:
a = .1
def gradient_function(w,x,b,a):
  m,n = x.shape
  dj_dw = np.zeros((n,))
  dj_db = 0
  for i in range(m):
    err = (np.dot(x[i], w) + b) - y[i]
    for j in range(n):
      dj_dw[j] = dj_dw[j] +err * x[i,j]
    dj_db = dj_db + err
  dj_dw = dj_dw/m
  dj_db = dj_db/m
  w = w - a*dj_dw
  b = b - a*dj_db
  return w,b
  print(f'The final value of w,b is {w,b}')

In [72]:
def grad_descent(x,y,w_in,b_in,cost_function,gradient_function,oneloop,alpha,num_iters):
  J_history = []
  w = copy.deepcopy(w_in)
  b = b_in
  for i in range(num_iters):
    cost = cost_function(w,x,b)
    gradient_function(w,x,b,alpha)
    if i<10000:
      J_history.append(cost)
    if i%math.ceil(num_iters/10)==0:
      print(f"Iteration {i:4}: Cost {float(J_history[-1]):8.2f}")
    J_history.append(cost)
  return w,b,J_history

In [73]:
initial_w = np.zeros_like(w_init)
initial_b = 0

iterations = 1000
alpha = 5.0e-7

w_final,b_final,J_hist = grad_descent(X_train,y_train,initial_w,initial_b,gradient_function,oneloop,alpha,iterations)
print(f"w by grad descent: {w_final}")
print(f"b by grad descent: {b_final}")
for i in range(m):
  print(f"prediction: {np.dot(X_train[i], w_final) + b_final:0.2f}, target value: {y_train[i]}")

TypeError: grad_descent() missing 1 required positional argument: 'num_iters'